volumes:
  pg_data:
  files:

services:
  db:
    image: postgres:13.15-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build: ./app/
    command: python main.py
    env_file: .env
    volumes: 
      - files:/app/files 
    depends_on:
      - db
  gateway:
    build: ./gateway/
    env_file: .env 
    ports:
      - 8000:80 
    depends_on:
      - app