"""add tags

Revision ID: 092f59863e91
Revises: 33d7dcae98c9
Create Date: 2024-11-27 16:44:11.216525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092f59863e91'
down_revision: Union[str, None] = '33d7dcae98c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globaltag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('author', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['telegram_user.tg_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'author', name='uix_name_author')
    )
    op.create_table('file_customtag',
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('customtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customtag_id'], ['customtag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file.filehash'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'customtag_id')
    )
    op.create_table('file_globaltag',
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('globaltag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.filehash'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['globaltag_id'], ['globaltag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'globaltag_id')
    )
    op.create_unique_constraint(None, 'telegram_user', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_user', type_='unique')
    op.drop_table('file_globaltag')
    op.drop_table('file_customtag')
    op.drop_table('customtag')
    op.drop_table('globaltag')
    # ### end Alembic commands ###
