"""Change tg_id to BigInteger

Revision ID: 33d7dcae98c9
Revises: 9960e0cefd9d
Create Date: 2024-11-20 07:01:15.251434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d7dcae98c9'
down_revision: Union[str, None] = '9960e0cefd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'created_by',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.drop_constraint('file_created_by_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'telegram_user', [
                          'created_by'], ['tg_id'], ondelete='SET NULL')
    op.alter_column('telegram_user', 'tg_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_user', 'tg_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'telegram_user',
                          ['created_by'], ['tg_id'])
    op.alter_column('file', 'created_by',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
